#!/bin/bash
set -ue
set -x

remote_host=`relation-get private-address`
export_path=`relation-get mountpoint`
fstype=`relation-get fstype`
if [ -z "$export_path" ] ; then
    juju-log "remote host not set yet."
    exit 0
fi

local_mountpoint="/home/ubuntu/shared"
local_owner="ubuntu"
mount_options=""

create_local_mountpoint() {
  juju-log "creating local mountpoint"
  umask 002
  mkdir -p $local_mountpoint
  # create owner if necessary?
  chown -f $local_owner.$local_owner $local_mountpoint
}
[ -d $local_mountpoint ] || create_local_mountpoint 

share_already_mounted() {
  `mount | grep -q $local_mountpoint`
}
mount_share() {
  for try in {1..3}; do

    juju-log "mounting nfs share"
    [ ! -z $mount_options ] && options="-o ${mount_options}" || options=""
    mount -t $fstype $options $remote_host:$export_path $local_mountpoint \
      && break

    juju-log "mount failed: $local_mountpoint"
    sleep 10

  done
}
share_already_mounted || mount_share 

juju-log "Configuring cherokee"

site_name=`relation-get site_name`
python_path=`relation-get python_path`
webroot=`relation-get webroot`
wsgi_file=`relation-get wsgi_file`
virtualenv=`relation-get virtualenv`

CHEROKEE_CONFIG="/etc/cherokee/cherokee.conf"
juju-log "Writing config file $CHEROKEE_CONFIG"
cp config/cherokee.conf $CHEROKEE_CONFIG
sed -i -e "s:@@USERNAME@@:ubuntu:g" \
  -e "s:@@USERGROUP@@:ubuntu:g" \
  -e "s:@@SITENAME@@:$site_name:g" \
  -e "s:@@PYTHONPATH@@:/home/ubuntu/shared/$python_path:g" \
  -e "s:@@WEBROOT@@:/home/ubuntu/shared/$webroot:g" \
  -e "s/@@WSGI@@/reeder.wsgi/g" \
  -e "s:@@VIRTUALENV@@:/home/ubuntu/shared/$virtualenv:g" \
  $CHEROKEE_CONFIG


# Make it publicly visible, once the service is exposed
open-port 80/tcp

juju-log "Restarting Cherokee server"
/etc/init.d/cherokee restart


