#!/bin/bash

set -e

DEBIAN_FRONTEND=noninteractive apt-get -y install -qq haproxy pound

cat > /etc/default/haproxy <<EOF
ENABLED=1
EOF

cat > /etc/default/pound <<EOF
startup=1
EOF

# We actually want it stopped until at least one thing has joined
service haproxy stop
service pound stop

cp config/ssl-cert-snakeoil.pem /etc/ssl/certs/ssl-cert.pem 
